server:
  port: ${GATEWAY_PORT:8082}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      
      # --- AQUÍ EMPIEZA LA MAGIA DE LAS RUTAS ---
      routes:
# --- MICROSERVICIO 3 (USUARIOS) ---
        - id: microservicio3
          uri: lb://MICROSERVICIO7  # <--- Mayúsculas, vital para Eureka
          predicates:
            # Atrapa la llamada que hace tu front (/api/users/...)
            - Path=/api/users/**
          filters:
            # QUITA el "/api" (el primer segmento) antes de pasarlo al microservicio
            # Así llega como "/users/create"
            - StripPrefix=1

        # --- MICROSERVICIO 1 (TOOLS / CATCH-ALL) ---
        - id: microservicio1
          uri: lb://MICROSERVICIO1
          predicates:
            - Path=/**