server:
  port: ${GATEWAY_PORT:8082}

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka-service:8761/eureka/
  instance:
    prefer-ip-address: true

spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      default-filters:
        - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: '*'
            allowedMethods: "*"
            allowedHeaders: "*"
      
      # --- AQUÍ EMPIEZA LA MAGIA DE LAS RUTAS ---
      routes:
        # 1. RUTAS DEL MICROSERVICIO 3 (USUARIOS)
        # Deben ir PRIMERO si vas a usar un catch-all (/**) al final
        - id: microservicio3
          uri: lb://MICROSERVICIO3
          predicates:
            # Pon aquí las rutas que maneja tu MS3. 
            # Si tu front llama a /users/register, pon /users/**
            # Si llama a /auth/login, pon /auth/**
            # Puedes poner varias separadas por coma.
            - Path=/users/**, /auth/**, /api/users/** # 2. RUTAS DEL MICROSERVICIO 1 (TOOLS)
        # Esta se queda con el resto del tráfico (Catch-all)
        - id: microservicio1
          uri: lb://MICROSERVICIO1
          predicates:
            - Path=/**